version: "3"

tasks:
  dev:
    cmds:
      - air

  server:
    cmds:
      - go run ./examples/server .

  client-desktop:
    cmds:
      - go run ./examples/ebiten-client-desktop .

  gomp-server:
    cmds:
      - go run ./pkg/ebiten-ecs/examples/gomp-server .

  gomp-client:
    cmds:
      - go run ./pkg/ebiten-ecs/examples/gomp-ebiten-client .

  build-web-client:
    cmds:
      - env GOOS=js GOARCH=wasm go build -o ./.dist/web-ebiten-client.wasm ./examples/web-ebiten-client-ws/main.go
      - cp $(go env GOROOT)/misc/wasm/wasm_exec.js ./.dist

  proto:
    cmds:
      - protoc --go_out=. internal/**/*.proto

  pprof-cpu:
    cmds:
      - go tool pprof -http=":8000" ./cpu.out

  pprof-mem:
    cmds:
      - go tool pprof -http=":8001" ./mem.out

  pprof-trace:
    cmds:
      - go tool trace trace.out

  build-win64:
    env:
      CGO_ENABLED: 1
    cmds:
      - go build -o ./.dist/game-win64.exe examples/new-api/game.go
#      - go build -o ./.dist/cgo-game.exe internal/sdl3-pure/sdl-game.go
#      - CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -tags static -ldflags "-s -w" internal/sdl2/sdl-game.go

  build-mac:
    - task: build-darwin-amd64
    - task: build-darwin-arm64
    - task: build-darwin-universal
    - task: sign-darwin-universal

  build-darwin-amd64:
    env:
      CGO_ENABLED: 1
    cmds:
      - env CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o ./.dist/game-darwin-amd64 examples/new-api/game.go
      - chmod +x ./.dist/game-darwin-amd64

  build-darwin-arm64:
    env:
      CGO_ENABLED: 1
    cmds:
      - env CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o ./.dist/game-darwin-arm64 examples/new-api/game.go
      - chmod +x ./.dist/game-darwin-arm64

  build-darwin-universal:
    cmds:
      - lipo -create -output ./.dist/game-universal ./.dist/game-darwin-amd64 ./.dist/game-darwin-arm64
      - chmod +x ./.dist/game-universal

  sign-darwin-universal:
    cmds:
      - mkdir -p ./.dist/game.app/Contents/MacOS
      - mv ./.dist/game-universal ./.dist/game.app/Contents/MacOS/game
      - chmod +x ./.dist/game.app
      - codesign --timestamp --options=runtime --deep -fs milanrodd-cert -v ./.dist/game.app
      - xattr -cr ./.dist/game.app
      - /usr/bin/ditto -c -k --keepParent ./.dist/game.app ./.dist/game.zip
